markdown: kramdown
highlighter: rouge

version:
    jquery: 3.1.1
    semantic_ui: 2.2.8
    font_awesome: 4.7.0
    moment: 2.17.1
    count_up: 1.8.1
    echarts: 3.4.0
    js_cookie: 2.1.3

google_analytics_id: UA-33449675-7
piwik_analytics:
    site_id: 1
    url: https://vps.irockbunny.com/analytics/?callback=?
    token: f415eff9302de22d195d1d87b092c825

repository: https://github.com/iROCKBUNNY/BYR-Navi

timezone: Asia/Shanghai

name: 北邮人导航 · BYR-Navi
author: iROCKBUNNY
description: A Navigation Website for BYR
keywords: 北邮人导航, BYR-Navi, BYR, BUPT, Navi, Navigation
url: http://story.irockbunny.com
contact: contact[at]irockbunny[dot]com

favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png
logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

gems:
    - jekyll-seo-tag
    - jekyll-sitemap

exclude:
    - .gitignore
    - LICENSE
    - README.md